pinecone/core/grpc/index_grpc.py, pinecone/core/utils/__init__.py
=> Fix grpc imports

pinecone/__init__.py
=> Handle ImportError gracefully for non-grpc clients

pinecone/core/client/model/scored_vector.py, pinecone/core/client/model/vector.py, pinecone/core/grpc/protos/vector_service_pb2.py, specs/pinecone_api.json, specs/vector_service.openapi.json
Update request limits like the maximum number of vectors, ids, etc.
[ch9820]
=> update API spec with new request limits

pinecone/manage.py
Reverts pinecone-io/pinecone-python-client#23
=> Revert "Add pods and pod_type to create_index"

pinecone/manage.py
Reverts pinecone-io/pinecone-python-client#24
=> Revert "Revert "Add pods and pod_type to create_index""

specs/index_service.json
These changes were made to generate updates to the core repo. See [core repo PR#1097](https://github.com/pinecone-io/core/pull/1097)
=> Copy updates to index_service.json from core repo.

pinecone/core/client/model/query_request.py, pinecone/core/grpc/index_grpc.py, pinecone/index.py, tests/unit/test_grpc_index.py, tests/unit/test_index.py, tox.ini
This PR cleans current code while keeping 100% backwards compatibility, by:
1. add explicit arguments and types
2. add documentation
3. add unit tests for all arguments combinations
=> Refactor API args and add documentation 

pinecone/core/grpc/index_grpc.py, pinecone/index.py, requirements.txt, tests/unit/test_grpc_index.py, tests/unit/test_index.py
Implement batch upsert within existing upsert call (only for sync calls)
=> Batch upsert

pinecone/core/grpc/index_grpc.py
1. Replaced the current implementation of gRPC retries which used an interceptor with a direct config of the gRPC layer itself.
2. Shortened `maxBackoff` from 1.6 sec to 1 sec. When this time is too long, it seems that we're starting to get server-side rejects ("GOAWAY") since the retry messages are still trying to use an old channel.
3. Fixed a bug where `future.result()` for async requests was actually returning `None`s.
=> Use built-in gRPC retry configuration

tests/unit/test_grpc_index.py
I added a unit test for `upsert(GRPCVector)` with sparse values.  
While at it - I also done some syntax changes in the tests, to slightly reduce code duplication.
Note: we need to also add sparse test to the Rest index later.
=> Sparse values unit test

tests/unit/test_grpc_index.py
- Test all possible input combination.
- Negative tests for missing \ excess keys
- Negative tests for wrong data types
=> Added upsert(dict) unit tests

pinecone/index.py, requirements.txt, tests/unit/test_grpc_index.py
- Test "happy path"
- Test sync upload
- Negative testing
Note: Only added tests for GRPCIndex, need to add tests for Rest Index in the future
=> Added UT for upsert_dataframe()

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
Improve issue resolution process with templates
=> Introduce Feature & Issue Templates

.github/actions/build-docs/action.yml, .github/workflows/merge.yaml, .github/workflows/pr.yaml
This is a cherry-pick of changes in #234 onto the spruce branch. I want this change in both `main` and `spruce` but rebasing spruce or merging main into spruce is complicated due to the number of open PR branches on spruce at the moment.
Describe the approach you took. Link to any relevant bugs, issues, docs, or other resources.
=> [spruce] Pin docs-build python version

poetry.lock, pyproject.toml
Some dependencies not being used.
Remove unused deps with `poetry remove`:
- `pyyaml`
- `pythondns`
- `loguru`
=> Remove unused deps

.github/actions/build-docs/action.yml, .github/workflows/merge.yaml, CONTRIBUTING.md, README.md, pinecone/control/pinecone.py, pinecone/grpc/__init__.py, pinecone/grpc/pinecone.py, pinecone/models/collection_description.py, pinecone/models/collection_list.py, pinecone/models/index_description.py, pinecone/models/pod_spec.py, tests/integration/control/test_configure_pod_index.py
Update the docs and bring back the docs publishing workflow step.
=> Update documentation for v3.0 release

pinecone/utils/constants.py
I noticed there are a few constants defined that are not currently being used anywhere.
- Search in codebase to confirm these are no longer in use.
- Remove them.
See tests still pass.
=> Remove unused constants

README.md
CI Badge seems broken
Remove it
=> Drop broken README badge

README.md
Need to update README with content about deletion protection and inference.
Update examples
=> Readme changes for v5 release.

.github/workflows/testing-integration.yaml
Some tests were being run with large dimensions. This leads to log output that is slow to load and difficult to read when things go wrong in CI.
Reduce the test dimension.
=> Reduce dimension in testing to simplify output

codegen/build-oas.sh
Describe the approach you took. Link to any relevant bugs, issues, docs, or other resources.
=> Update build-oas script for building exceptions template changes

CONTRIBUTING.md
Poetry shell is now a plugin that should be installed separately.
=> Update CONTRIBUTING.md with Poetry shell install

README.md
`uv add` instead of `uv install`
=> Fix UV command

pinecone/db_control/resources/asyncio/index.py, pinecone/db_control/resources/sync/index.py
After creating an index, the SDK polls until the index is ready to be used. But if the index state transitions to `InitializationFailed`, the client will hang. Sometimes this causes our test suite to get stuck and run for hours until somebody manually intervenes or a CI timeout is reached.
Raise an exception and stop waiting if an index reaches the `InitializationFailed` state.
=> Stop waiting if `InitializationFailed` state is reached
