pinecone-io/pinecone-python-client

- pinecone/index.py
While running integration tests against pinecone, I got:
```
../related-content-api/lib/python3.8/site-packages/pinecone/index.py:5
/Users/chelseatroy/workspace/related-content-api/related-content-api/lib/python3.8/site-packages/pinecone/index.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import Iterable
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
This one-line change addresses that warning.
> Fix depcrecation warning that interrupts users' testing/use flow

- pinecone/core/grpc/index_grpc.py
A client-side fix for SC-10724.
> Default describe_index_stats response namespaces to empty dict

- setup.py
This is to change the pypi project page to show the github readme contents and link correctly to pinecone.io/docs
> Update pypi distribution docs link and readme

- README.md
This PR adds all of the custom Python examples from the pinecone-protos repo into the README file for the Pinecone Python client. The goal is to separate the Python client documentation from the API documentation; when we switch from our current Redocly documentation platform to Readme.io, we will only display the autogenerated Python sample code, which uses generic request operations to access the API. See docs.pinecone.io/reference, password: freshpinescent
> Add create index examples to README.md file.

- pinecone/config.py
- pinecone/core/utils/constants.py
It seems that OpenAPI's inherent Rest client uses connection pooling without a keep alive mechanism.  
In some cases, the client keeps holding an idle connection for long periods (>15 min), yet the server (Pinecone's load balancer) seem to be terminating the connection after ~10 minutes of idleness.  
I've configured OpenAPI's client to enable Keep Alive for all connections. Since the LB is configured to terminate the connection regardless of keep alive, this won't lead to having many dangling connections.  
The main benefit is having the client "finding out" early about the dropped connection, so it won't try to use it for the next user request.  
I've tested the solution (manually) on Both Mac OS, Linux and Windows Server OSes - and it seems to resolve the failure.
> Fix "Connection Reset by peer" error after long idle periods

- pinecone/core/grpc/index_grpc.py
We believe the type checking takes a long time which adds a lot of query latency.
I've added proper handling of the `_check_type` arg in `GRPCIndex.query()`, with default `False`.  
This argument is now correctly passed to `parse_query_response()`, which should save a lot of time for queries with large `top_k`
> Use _check_type=False in GRPCIndex.query()

- pinecone/core/grpc/index_grpc.py
- pinecone/core/utils/constants.py
- pinecone/index.py
Upsert will now accept vectors represented as dicts. This provides a nice way to pass vectors with sparse values, rather than isntantiating `Vector()` objects
Also, this will allow us to represent entire datasets in the future as dataframes, where each vector is a dictionary (one row of the dataframe).
> Index.upsert() now accepts List[dict]

- pinecone/core/grpc/index_grpc.py
- pinecone/index.py
1. Added verification that the input is `pd.Dataframe`
1. Return the proper result type (`UpsertResponse`) with the total upserted number.
2. For gRPC - support both async and non-async modes
3. Renamed to `upsert_from_dataframe()`
> Upsert dataframe - support non-async option

- pinecone/core/grpc/index_grpc.py
- pinecone/index.py
In case the user passed a vector with metadata but without sparse values, the metadata was simply ignored.  
(Caught by new UTs, which are coming in a separate PR).
The clause that parsed the `metadata` key was accidentally indented under the `if sparse_values` clause...
> Bug fix upsert(dict)

- tests/unit/test_config.py
A lot of refactoring is needed in `init()` method to remove various UX footguns, improve performance (e.g. whoami), and give better error messages when the client is misconfigured. But before we can safely do any of that, we need to add a lot of missing tests to document the existing behavior of the `init()` method.
https://app.asana.com/0/1203260648987893/1204499608161625/f
> Backfill missing unit tests for pinecone.init() method

- .github/workflows/pr.yaml
- test-requirements.txt
- tests/unit/test_config.py
- tests/unit/test_grpc_index.py
- tox.ini
I discovered recently that tests have not been running in CI because some configuration for our test orchestrator [`tox`](https://tox.wiki/en/latest/config.html) were [accidentally removed](https://github.com/pinecone-io/pinecone-python-client/commit/10fb42c2983b731700ffe89183994cd4e1844020). This fact was obscured because the CI configuration specifying a matrix of python versions to test meant several versions of the workflow were kicking off, but if you look carefully you'd see no tests were actually executing.
1. Add and iterate on configuration to `tox.ini`, the configuration for the tox test orchestrator. I'm new to this tool, but it seems that tox works in conjunction with [tox-gh-actions](https://github.com/ymyzk/tox-gh-actions) and the github matrix strategy to execute tests on …
> Fix tox configs for CI testing

- .github/workflows/pr.yaml
- pinecone/core/utils/__init__.py
- pinecone/index.py
- requirements.txt
- tests/unit/test_index.py
Need to update numpy dependency version to pull in recent security updates. In the future we plan to remove our direct dependency on numpy.
- Update numpy to >= 1.22.0
- Add deprecation notices where numpy is currently being used. Notices are emitted using the `warnings` [package from the Python standard library](https://docs.python.org/3.8/library/warnings.html) which will only display the message one time.
- Adjust our deprecation utility to emit warning type `FutureWarning` because `DeprecationWarning` is suppressed by default and almost nobody will see it. 
- The deprecation warning messages give guidance on how to fix usage, but if anyone wants to suppress the messages without making a change right now, they should add this to their code.
```py
import warnings …
```
> Update numpy dependency version

- setup.py
Recently removed code related to python 3.7 support because it is EOL, but forgot to include this change to setup.py where we declare what version of python is required.
Adjust the setup.py configuration.
> Update python_requires to 3.8

- .github/workflows/publish-to-pypi.yaml
Prod release builds currently fail because the required prereleaseSuffix input is not being passed to the shared workflow `publish-to-pypi.yaml`
This is a follow up to #178 Release from CI
There's no reason for this property to be required; the bump version action correctly handles the scenario where that value is not passed.
This issue causes failures like [this one](https://github.com/pinecone-io/pinecone-python-client/actions/runs/5195718175).
Land and try shipping again 🤣
> Fix prod pypi release by adjusting shared publish workflow

- .github/workflows/alpha-release.yaml
- .github/workflows/nightly-release.yaml
- .github/workflows/publish-to-pypi.yaml
- .github/workflows/release.yaml
We need a way to consume unreleased changes for integration testing purposes.
Publish each night, if there are new changes, using the package name `python-client-nightly`. This follows the practice of other large projects such as `tensorflow` which publishes nightlies under the `tf-nightly` name. PyPI does have some limited support for prereleases but releasing a lot of them under our normal package name will make the release history page on pypi look quite cluttered.
I successfully used this to publish to testpypi. Just changed a few variables to point at the public index.
> Nightly python builds

- pinecone/index.py
Typo in the documentation
Fix the spelling mistake.
Not needed?
> Typo in docstring for upsert()

- pinecone/core/client/rest.py
See gh-125
This PR simply replaces the deprecated `HTTPResponse.getheader()` usages with the suggested `HTTResponse.headers`.
> Replace deprecated HTTPResponse.getheader()

- pinecone/core/client/rest.py
Follow up to #195, which updated to use `urllib.headers` -- there's also a deprecation for `getheader` coming: https://github.com/urllib3/urllib3/pull/2814
Updated the call in `rest.py` to use `.get` instead of `.getheader`; based on the [code](https://github.com/urllib3/urllib3/blob/1.2.1/urllib3/response.py#L191C29-L191C32) this should be compatible with 1.2.1, [our current min version](https://github.com/pinecone-io/pinecone-python-client/blob/main/requirements.txt#L8)
REST requests should work without a notice in URLLib3 2.0.4+
> update urllib3_response.headers.get as getheader is deprecated

- pinecone/config.py
- pinecone/core/utils/__init__.py
- pinecone/core/utils/check_kwargs.py
- tests/unit/test_config.py
Per #196 a typo in init's kwargs results in a default that might not be expected.
Utils now includes check_kwargs, which takes a caller + the given kwargs, and fails with a traceback if they don't match.
cc @jhamon @austin-denoble @rohanshah18 
1) Where else should we use check_kwargs?
2) Is the traceback useful? in this instance it risks leaking api keys into logs, so for `init` in particular i question its value.
`pinecone.init(not_a_kwarg='foo')` should fail
> adds util for checking kwargs, and uses it to check init()

- .github/workflows/nightly-release.yaml
- pyproject.toml
After the poetry migration in https://github.com/pinecone-io/pinecone-python-client/pull/193 the `PyPI Release: Nightly (pinecone-client-nightly)` has been failing: https://github.com/pinecone-io/pinecone-python-client/actions/runs/6374232183/job/17298658421
The reason is we removed the `setup.py` file as a part of the migration and `nightly-release.yaml` used to adjust the module name via `sed -i 's/pinecone-client/pinecone-client-nightly/g' setup.py`. To achieve something similar now that we've changed our build / packaging process to use Poetry, we need to look at updating the `pyproject.toml` file.
While looking at correcting this, I realized the resulting build artifacts from `make package` (which now calls `poetry build`) now have different package names which may cause issues with …
> Fix nightly-release workflow and tweak Poetry package naming

- .github/actions/setup-poetry/action.yml
- .github/workflows/nightly-release.yaml
- .github/workflows/publish-to-pypi.yaml
- .github/workflows/testing.yaml
`nightly-release` workflow is still failing after the previous "fix": https://github.com/pinecone-io/pinecone-python-client/pull/208.
This time it's due to `make package` failing on `poetry build`, because `poetry` wasn't setup properly in the workflow.
https://github.com/pinecone-io/pinecone-python-client/actions/runs/6399744230/job/17372332268
> Run make package
poetry build
make: poetry: No such file or directory
make: *** [Makefile:22: package] Error [12](https://github.com/pinecone-io/pinecone-python-client/actions/runs/6399744230/job/17372332268#step:9:13)7
Error: Process completed with exit code 2.
While fixing this I noticed we're also not installing Poetry in the `publish-to-pypi` workflow, so calling `poetry version` and `make` commands there would fail. We need to make sure …
> Add new setup-poetry action and fix nightly-release

- .github/workflows/merge.yaml
The PR for adding pdoc integration via GitHub workflows was just merged: https://github.com/pinecone-io/pinecone-python-client/pull/207
The workflow is failing because we're not initially checking things out:
https://github.com/pinecone-io/pinecone-python-client/actions/runs/6421593962/job/17436307034
>Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/pinecone-python-client/pinecone-python-client/.github/actions/build-docs'. Did you forget to run actions/checkout before running your local action?
- Add the `actions/checkout@v3` step to the start of the workflow
I really need to get tooling setup to run these workflows locally to validate. This is a very tiny change and we should be able to re-evaluate on the merge. 😅
> Fix merge workflow by adding checkout step

- .github/actions/bump-version/action.js
- .github/workflows/nightly-spruce-dev-release.yaml
- .github/workflows/release-spruce.yaml
- Makefile
We need a way to ship builds of the `spruce` branch.
Modify existing workflows for `nightly-release` and `release` for shipping artifacts to Test PyPI.
Workflows update `pyproject.toml` `name` field: `pinecone-client-spruce-dev` and `pinecone-client-spruce`:
- `pinecone-client-spruce` releases are for use in 3rd party testing
- `pinecone-client-spruce-dev` releases are for use in internal testing
Trigger and validate workflows either locally or from the repo directly.
> Spruce release workflows

- .github/workflows/nightly-spruce-dev-release.yaml
- .github/workflows/release-spruce.yaml
- Makefile
For managing Spruce artifacts I added a new command in the makefile, but I didn't update `.PHONY:` at the top of the file to include the new command. 
- Add `upload-spruce` to `.PHONY:` in the Makefile.
- Remove some unneeded `ids` from `release-spruce` and `nightly-spruce-dev-release`.
Re-run workflows with corrected make.
> Fix Spruce workflows

- pinecone/manage.py
- tests/unit/test_grpc_index.py
- tests/unit/test_index.py
- tests/unit/test_manage.py
We need support for supplying a custom `host` value for index operations.
`pinecone.init()` and `Config` already support the ability to supply a custom `host`. It didn't seem like it was being passed through to the `ApiClient`:
- Update `_get_api_instance()` in `manage.py` to check for a `Config.CONTROLLER_HOST` value, and apply it to the `client_config` if so. This will then be used throughout the index operations.
- Add a unit test file for `manage.py`, test setting `controller_host` and timeout functionality in `create_index` / `delete_index`.
Pull this branch down and test locally. I validated myself by passing a bogus `host` in and looking over the errors, then passing the proper `host` via `init` to validate it works properly.
```python
>>> poetry shell
>>> python3
>>> import …
```
> Support passing custom host for Index operations

- pinecone/manage.py
Previous revision we added some code to apply a custom `host` value to control plane operations: https://github.com/pinecone-io/pinecone-python-client/pull/218
This change caused 404s when calling dataplane operations. The `Configuration._base_path` value was being overwritten by the custom `host` that was provided due to the `Configuration.host` setter:
```
@host.setter
def host(self, value):
"""Fix base path."""
self._base_path = value
self.server_index = None
```
https://github.com/pinecone-io/pinecone-python-client/blob/7ff4ed877ac3e97eb557b747a072a84e57764b91/pinecone/core/client/configuration.py#L493
The change I made was actually modifying the reference to `Config.OPENAPI_CONFIG` which overwrote things across the board.
Instead of operating on the singleton's instance of the …
> Prevent _get_api_instance from modifying OpenAPI config

- .github/workflows/merge.yaml
(These are basically the same changes as the TypeScript client, PR info is the same: https://github.com/pinecone-io/pinecone-ts-client/pull/146)
The current flow for building and deploying documentation for SDK clients takes place within each repository. Currently, `merge` workflows handle the docs build step, and pushing the contents of the generated `/docs` folder to a specific branch for each client: `gh-pages`. This branch is then used as the deployment source for GitHub pages.
There are several issues intrinsic in this:
- We have to manage each CI configuration and deployment on a per-repo basis.
- Applying custom sub-domains to our GitHub pages instances is difficult, and we would need to define a specific sub-domain for each repo.
- We're unable to share resources or assets across …
> [Docs] Update merge workflow to push generated artifacts to sdk-docs repo

- .github/actions/build-docs/action.yml
- .github/workflows/merge.yaml
- .github/workflows/pr.yaml
The build-docs workflow action has been failing since `setup-python`, which was configured with floating version `3.x`, rolled over to install the new 3.12 cpython release.
Pin to cpython 3.11 so things can build while we do more investigation about how to unblock running with 3.12.
See builds passing again.
> Pin docs-build python version

- poetry.lock
- pyproject.toml
Dependabot shows a vulnerability in one of our dev dependencies https://github.com/pinecone-io/pinecone-python-client/security/dependabot/7
Bump to a version with the fix, pytest 7.2.0, and confirm tests still run.
> [spruce] Bump to pytest 7.2.0 to fix security issue

- poetry.lock
- pyproject.toml
Dependabot shows a vulnerability in one of our dev dependencies https://github.com/pinecone-io/pinecone-python-client/security/dependabot/7
Bump to a version with the fix, pytest 7.2.0, and confirm tests still run.
> Bump to pytest 7.2.0 to fix security issue

- pinecone/config/config.py
- pinecone/config/pinecone_config.py
- pinecone/control/pinecone.py
- tests/unit/test_control.py
To support API development and testing, we would like a way to pass additional headers with every request.
Add a new `additional_headers` config option and wire up the api client internals to use them.
Usage:
```python
p = Pinecone(api_key='asdf', additional_headers={'X-SECRET-EXTRAS': 'secret secret'})
```
Added a unit test and also verified manually running with `PINECONE_DEBUG_CURL=true`
> [spruce] Add additional_headers config

- .github/workflows/publish-to-pypi.yaml
When we migrated to `poetry`, the prerelease job did not get updated to set prerelease versions correctly.
We need to use our action to compute the correct prerelease version.
> [Fix] Prelease CI job uses bump action to version

- pinecone/grpc/base.py
Currently, you cannot target an index using the `PineconeGRPC` client. `GRPCIndexBase._endpoint` is still trying to use `Config.PROJECT_NAME` and `Config.ENVIRONMENT` which have been deprecated.
Update `GRPCIndexBase` to properly leverage the `config` which is passed via `PineconeGRPC`. We also need to strip out the `https://` and keep the port `443`.
> [spruce] Allow GRPCIndexBase to use config.host to establish endpoint

- pinecone/control/pinecone.py
- tests/unit/models/test_index_list.py
There was a small error in a recent change to add a `names()` utility method on the response from `Pinecone#list_indexes` to facilitate easy iteration over index names. This resulted in an error when deleting indexes:
```
def get_remaining():
>       return name in api_instance.list_indexes().names()
E       TypeError: 'NoneType' object is not callable
```
This error got introduced because `api_instance.list_indexes()` and `self.list_indexes()` are both a thing in this context, but only `self.list_indexes()` returns a result with the `.names()` helper.
Call names on the correct object to avoid the error.
I confirmed with manual testing that this resolves the issue.
> [spruce] Fix issue with polling after delete index

- pinecone/core/client/model_utils.py
- tests/unit/data/test_datetime_parsing.py
Sometimes when strings are stored as metadata values, later fetching or querying causes those values to be coerced into datetime objects by the client before they are presented to the caller. This is a default behavior in the generated openapi client that is a result of the python `datetime` constructor working quite hard to turn things into dates. We've seen scenarios where this was not desired, so for now we will disable this conversion process to have consistent handling of all strings. People who desire date objects can easily implement the conversion themselves.
- Update openapi templates to comment out and remove logic related to converting strings into date and datetime objects.
- Regenerate client with new templates
- Add unit test verifying the type coercion does not take place. …
> [Bug] Stop coercion of strings into datetime objects

- pinecone/control/pinecone.py
- pinecone/grpc/pinecone.py
- tests/unit/test_config.py
We need to expose the `pool_threads` config in the new `Pinecone` constructor. This config property is ultimately used by the `ApiClient` class ([see here](https://github.com/pinecone-io/pinecone-python-client/blob/e81807de685d08297ea4ad642639fbc0d0ab24fd/pinecone/core/client/api_client.py#L61)), which is generated by the OpenAPI python generator. It is only used when performing operations over REST using the `async_req=True` param.
Add a property and wire it up with the underlying `ApiClient` object and `Index` constructor.
> Wire up pool_threads config

- pinecone/config/config.py
- pinecone/control/index_host_store.py
- pinecone/utils/__init__.py
- pinecone/utils/normalize_host.py
- tests/unit/test_config.py
- tests/unit/test_control.py
- tests/unit/utils/test_normalize_host.py
We want to make the client flexible enough to accept data plane host values both with and without the `https://` prefix. This is needed because the value is not prefixed with `https` in the describe_index response, but parts of the UI show the complete url with protocol.
Add a new util method to normalize the urls. Incorporate the util into the IndexHostStore and ConfigBuilder. The ConfigBuilder usage should cover both the `Index` and `IndexGRPC` milestones.
Added new unit tests of util.
> Accept host urls both with and without https prefix

- .github/workflows/alpha-release.yaml
- .github/workflows/nightly-release.yaml
- .github/workflows/release.yaml
In #263 we split our tests across two different workflows. We need to update our publishing workflows to find the test configurations in the new locations.
Replace references to `testing.yaml` with references to `testing-grpc.yaml` and `testing-rest.yaml`.
> Update publish workflows with new testing setup

- pinecone/data/index.py
- pinecone/grpc/__init__.py
- pinecone/grpc/index_grpc.py
- pinecone/grpc/utils.py
- pinecone/grpc/vector_factory_grpc.py
- tests/unit/test_index.py
- tests/unit_grpc/test_grpc_index_query.py
There was an argument on the `query()` method for passing multiple queries at once. This has long been deprecated in the API and SDK, so it's time to remove it.
- Clean up the `queries` option to both `Index#query` and `IndexGRPC#query`.
- Remove code no longer needed to interpret the many forms these query options could take
- Cleanup and simplify response parsing logic
- Remove related tests passing `queries` kwarg
Recently added integration test suite gives high confidence queries still work after this change.
> Remove deprecated `queries` option in `query()`

- pinecone/__init__.py
When loading our library in notebook settings, tqdm (progress bar widget) throws off an annoying warning even though it works fine. It's not a good look.
Suppress the warning using the `warnings` standard library.
> Suppress TqdmExperimentalWarning

- .github/workflows/merge.yaml
- README.md
Not ready to go live with new docs until we publish the release
Revert readme changes, disable SDK reference doc generation on main.
> Temporarily revert docs changes

- poetry.lock
- pyproject.toml
Recent integration testing with our published dev releases shows we are missing a dependency: `certifi`.
```
Traceback (most recent call last):
File "/home/runner/work/pinecone-python-client/pinecone-python-client/scripts/3.x/delete-all-indexes.py", line 4, in <module>
File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pinecone/__init__.py", line 4, in <module>
from .config import *
File "/opt/hostedtoolcache/Python/3.9.18/x[64](https://github.com/pinecone-io/pinecone-python-client/actions/runs/7514956364/job/20458392131#step:3:69)/lib/python3.9/site-packages/pinecone/config/__init__.py", line 4, in <module>
from .config import ConfigBuilder, Config
File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pinecone/config/c …
```
> Add missing certifi dependency

- pinecone/models/collection_list.py
- tests/unit/models/test_collection_list.py
The `list_indexes()` response has a convenience method that lets you easily get index names by chaining `.names()`. We want the same ergonomics on `list_collections()`.
Add test and adjust model for implementation. Now you should be able to do:
```python
if index_name not in pc.list_indexes.names():
if collection_name not in pc.list_collections.names():
```
> Add missing .names() for list_collections()

- pinecone/control/pinecone.py
Found this deprecated method while updating doc strings. It won't work in its current state, and it was described as deprecated in the Changelog 2 years ago.
> Remove deprecated scale_index method

- pinecone/control/pinecone.py
- pinecone/grpc/pinecone.py
- tests/integration/data/test_initialization.py
In production situations, it's important people be able to configure the client in a way that does not hit the control plane to find out the host url. This was possible, but now that I'm writing docs I realized this is cumbersome because the positional index name arg was still being required even though it wasn't being used in that scenario. 
We want it to be easy.
```python
from pinecone.grpc import PineconeGRPC
pc = PineconeGRPC(api_key="key")
index = pc.Index('blah')
index = pc.Index('required-but-unused-index-name', host='blah-24vnhz6.svc.apw5-4e34-81fa.pinecone.io')
```
```python
from pinecone.grpc import PineconeGRPC
pc = PineconeGRPC(api_key="key")
index = pc.Index('blah')
index = pc.Index(host='blah-24vnhz6.svc.apw5-4e34-81fa.pinecone.io')
index = pc.Index(name='blah', …
```
> Simplify passing host configuration direct to Index client

- pinecone/data/index.py
- pinecone/grpc/index_grpc.py
- tests/unit/test_index.py
- tests/unit_grpc/test_grpc_index_query.py
Currently the python SDK allows users to send a request that contains values for both the `id` and `vector` fields. This request doesn't make sense to the API since the `id` field, when provided, is used to look up a vector in the index whose values should be used as the query.
We'd like to give clear feedback to the user that this is not correct usage rather than showing empty results.
- Implement the validation as a simple if-statement. 
- Update docstrings.
Added unit tests for this error handling case
> Add `query()` validation to prevent sending both `id` and `vector`

- tests/integration/control/test_configure_pod_index.py
We temporarily disabled this integration test earlier after reporting a bug to the backend team. Now we can bring it back.
Enable test.
> Re-enable integration test for `configure_index`

- pinecone/data/index.py
- tests/unit/test_index.py
In v3.0, the order of arguments to `query()` was changed to reflect that `top_k` is required and should therefore come first in the list of parameters. This is unfortunate, since it means any usage relying on `vector` being the first positional parameter will see a cryptic error about passing two values of `top_k`. 
Disable positional arguments for this function. This allows us to throw an error message with clearer instructions to the user.
Added unit test.
```
>>> from pinecone import Pinecone
>>> pc = Pinecone(api_key='XXX')
>>> index = pc.Index('foo')
>>> index.query([0.1, 0.2], top_k=10)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/jhamon/workspace/pinecone-python-client/pinecone/utils/error_handling.py", line 10, in inner_func
return …
```
> Improve error message when using positional arguments with query()

- README.md
Some shells (e.g. zsh) treat the '[]' in the argument as a shell expansion, and fail to pass the correct argument to pip:
% pip3 install pinecone-client[grpc] 
zsh: no matches found: pinecone-client[grpc]
Fix by quoting the package name.
Confirmed install still works with zsh and bash on macOS.
> README.md: Update install steps to escape brackets

- pinecone/control/pinecone.py
- pinecone/grpc/__init__.py
- pinecone/grpc/config.py
- pinecone/grpc/pinecone.py
- tests/unit/test_control.py
- tests/unit_grpc/test_grpc_index_initialization.py
This PR addresses a few configuration-related issues:
- We moved `pool_threads` configuration up to the `Pinecone` client instance, but for backwards compatibility it would be nice to also allow it to be passed in the call to `pc.Index(host='your-host', pool_threads=5)`
- We need to expose `grpc_config` as a keyword param when targeting indexes via the grpc-flavored client.
- Pass through kwargs from `.Index()` to underlying Index class implementation
- Add unit tests making sure `pool_threads` and `grpc_config` handled correctly.
```python
pc = Pinecone(api_key='key', pool_threads=5)
pc.Index(host='host')
pc.upsert(...)
```
You can use syntax as before, or alternatively can do this:
```python
pc = Pinecone(api_key='key')
index = …
```
> Expose missing configurations for `grpc_config` and `pool_threads`

- pinecone/control/pinecone.py
- pinecone/data/index.py
- pinecone/grpc/base.py
- pinecone/grpc/config.py
- tests/unit/test_control.py
- tests/unit/test_index_initialization.py
- tests/unit_grpc/test_grpc_index_initialization.py
There are some debugging scenarios where, in order to debug or track a specific request, we would like the ability to pass additional headers with each request.
- Add `additional_headers` kwarg to `Index()` for REST calls
- Add `additional_metadata` field within existing `grpc_config` object for configuring equivalent for GRPC
- Add unit tests for both ways of doing it. Metadata is a [similar concept](https://grpc.io/docs/guides/metadata/) to http request headers in GRPC, not to be confused with vector metadata.
```python
pc = Pinecone(api_key='xxx')
index = pc.Index(
host='hosturl', 
additional_headers={ 'header-1': 'header-1-value' }
)
index.upsert(...)
```
```python
from pinecone.grpc import PineconeGRPC, GRPCClientConfig
pc = …
```
> Optional configs to pass `additional_headers`/`additional_metadata` to indexes

- pinecone/config/pinecone_config.py
- tests/unit/test_config.py
We need a way to attach special request headers in integration testing.
Add support for overriding additional_headers via the `PINECONE_ADDITIONAL_HEADERS` environment variable.
Unit tests
```
$ cd pinecone-python-client/
$ export PINECONE_ADDITIONAL_HEADERS='{"header": "value"}'
$ python3
>>> from pinecone import Pinecone
>>> client = Pinecone(api_key='key', host='host')
>>> vars(client)
{'config': ... additional_headers={'header': 'value'}), ...}
```
> Support overriding `additional_headers` with `PINECONE_ADDITIONAL_HEADERS` environment variable

- .github/actions/build-docs/action.yml
- .github/actions/bump-version/action.yml
- .github/actions/create-index-legacy/action.yml
- .github/actions/create-index/action.yml
- .github/actions/delete-index/action.yml
- .github/actions/test-data-plane/action.yaml
- .github/workflows/merge.yaml
- .github/workflows/nightly-release.yaml
- .github/workflows/pr.yaml
- .github/workflows/publish-to-pypi.yaml
- .github/workflows/testing-dependency.yaml
- .github/workflows/testing-integration.yaml
- .github/workflows/testing-unit.yaml
Our test runs produce a large number of warnings related to deprecated node16 usage. 
Update the version of the shared tasks we are using.
> Update github actions dependencies to fix warnings

- pinecone/grpc/index_grpc.py
For GRPCIndex.upsert_from_dataframe() there is a second progressbar
used when use_async_requests is true (the default) - 'collecting async
responses'. However this progressbar is always shown, even if
show_progress is false.
Make it respect the show_progress argument.
> upsert_from_dataframe: Hide all progressbars if !show_progress

- poetry.lock
- pyproject.toml
I could not run unit tests because pytest-timeout relies on distutils which was removed in python 3.12
Updated pytest-timeout
Run all unit tests. Does not impact the actual client.
> Update pytest-timeout to support python >= 3.12

- README.md
@haruska pointed out that the headers in the SDK client reference navigation bar were a little off for "Create Index" showing "Create a pod index" only. The formatting also felt a bit off with everything being aligned.
https://sdk.pinecone.io/python/pinecone.html
While fixing this I also noticed the link for the `CONTRIBUTING.md` file is relative in the README, which doesn't work when linking from our generated docs.
- Promote "Indexes" to a top-level section to visually break up the nav list a bit, and then swap `Create Index` to the header and moving `Create a serverless index` and `Create a pod index` to sub-headers of that.
- Link directly to github for the `CONTRIBUTING.md` file. 
|Before|After|
| ------------- | ------------- |
|<img width="1166" alt="Screenshot 2024-02-23 at 12 55 …
> Fix minor README docs issues in client reference

- README.md
- pinecone/data/index.py
- pinecone/grpc/index_grpc.py
- pinecone/models/list_response.py
- tests/integration/data/conftest.py
- tests/integration/data/seed.py
- tests/integration/data/test_list.py
- tests/integration/data/test_list_errors.py
Need to implement the new data plane list endpoint.
- Update generated code. Pull in list endpoint. All changes under `pinecone/core` are generated from spec files and can be ignored for this review.
- Implement changes for list endpoint in:
- `pinecone/data/index.py` main implementation
- `pinecone/grpc/index_grpc.py` main implementation
- `tests/integration/data/conftest.py` adjustments to test setup, mainly to generate a new namespace to hold vectors for list testing data.
- `tests/integration/data/seed.py` to upsert a larger number of vectors, so I would have enough data to page through
- `tests/integration/data/test_list.py`
-  `tests/integration/data/test_list_errors.py`
- Do we expect to ever return more data than just `{'id': '1'}` in the vectors array? For convenience the …
> List vector ids by prefix

- pinecone/config/config.py
- pinecone/control/pinecone.py
- pinecone/data/index.py
- pinecone/utils/__init__.py
- pinecone/utils/setup_openapi_client.py
- tests/integration/data/conftest.py
- tests/integration/data/test_openapi_configuration.py
- tests/unit/test_config.py
- tests/unit/test_config_builder.py
- tests/unit/test_control.py
- tests/unit/test_index_initialization.py
A few different problems being solved here:
- `Pinecone` class accepts an optional param, `openapi_config`. When this is passed (usually as a vehicle for SSL configurations), it currently clobbers the `api_key` param so the user sees an error message about not providing an api_key (even though they did pass it) if they attempt to perform a control plane operation
```python
from pinecone.core.client.configuration import Configuration as OpenApiConfiguration
openapi_config = OpenApiConfiguration()
openapi_config.ssl_ca_cert = '/path/to/cert'
pc = Pinecone(api_key='key, openapi_config=openapi_config)
pc.list_indexes() // error: No api-key provided
```
- In a related issue, the `openapi_config` (with SSL configs) was not being correctly passed through to the …
> [Fix] Configuring SSL proxy via openapi_config object

- .github/workflows/testing-unit.yaml
- pinecone/data/__init__.py
- pinecone/data/errors.py
- pinecone/data/sparse_vector_factory.py
- pinecone/data/vector_factory.py
- pinecone/exceptions.py
- pinecone/grpc/sparse_values_factory.py
- pinecone/grpc/vector_factory_grpc.py
- pinecone/utils/convert_to_list.py
- tests/integration/data/test_upsert_errors.py
- tests/unit/data/test_vector_factory.py
- tests/unit/utils/test_convert_to_list.py
- tests/unit_grpc/test_sparse_values_factory.py
- tests/unit_grpc/test_vector_factory_grpc.py
There is a small number of unit tests that should only get run when grpc dependencies are installed. These were previously omitted from CI by mistake.
Add a step to run these grpc steps. Make it conditional on the `use_grpc` test matrix param.
> Add grpc unit test run, expand testing of VectorFactory

- pinecone/config/openapi.py
- pinecone/control/pinecone.py
A deprecation warning about openapi_config was appearing even when users were not passing in that keyword parameter. 
One of the things that makes the `openapi_config` object (instance of `OpenApiConfiguration`, a generated class) difficult to work with is that it carries a large amount of state; some of the fields inside of it are essentially constant (e.g. API key header) and others need to be adjusted based on which index you are trying to upsert/query/etc from. But you can't simply update those host values because multiple `Index` client objects could be sharing the same object reference. Consequently, a `copy()` method was added to make a deepcopy of this object before modifying any configuration properties when targeting an index.
For similar reasons, the same `copy()` method was …
> [Fix] openapi_config deprecation warning incorrectly shown

- .github/workflows/build-and-publish-docs.yaml
Currently, we have a couple different GitHub workflows which deal with building and publishing the client reference documentation:
- `merge.yaml`
- `build-and-publish-docs.yaml`
`merge` calls `build-and-publish-docs` on every merge to `main`. This is problematic as any changes that are made which change documentation will be reflected at in the [Python client reference](https://sdk.pinecone.io/python) as soon as they are merged to main even if we haven't cut a release.
- Remove the `merge.yaml` workflow entirely. Previously it was only dealing with building and deploying the reference docs.
- Update `build-and-publish-docs` to be a manually runnable or callable from another workflow.
For now, we can manually trigger new reference docs builds as needed, most likely after we cut a release. …
> Remove `merge` workflow and update `build-and-publish-docs` workflow to be manually runnable

- README.md
The serverless public preview warnings from January are still in documentation. Since we've expanded the number of regions available, we should tweak these callouts.
Update the "Create serverless index" example in the README. There were also some md auto-formatting bits that got pulled in here.
CI, run the client reference action after merging to main to update reference docs.
> Remove serverless public preview warnings

- pinecone/grpc/base.py
- pinecone/grpc/pinecone.py
- tests/integration/proxy_config/conftest.py
- tests/integration/proxy_config/test_proxy_settings.py
The PineconeGRPC client does not currently honor the proxy_url and ssl_ca_certs arguments - they are accepted but silently ignored.
This means the gRPC client cannot be used in enviroments which require a proxy to access the Pinecone service.
Address by wiring up these two config options to the corresponding options in the underlying grpc library - in addition to them still being passed to the HTTP-based control-plane connections.
Usage is very similar to the non-gRPC client - for example:
pc = PineconeGRPC(my_api_key,
proxy_url="http://localhost:8080",
ssl_ca_certs="/path/to/my/ca-cert.pem")
Proxy tests expanded to also test PineconeGRPC
> Support proxy_url and ssl_ca_certs options for gRPC

- pinecone/grpc/base.py
gRPC has a built-in retry mechanism[1] which we configure to automatically retry on status UNAVAILABLE messages from Pinecone.
However, it has been observed that VectorService/Upsert method is _not_ being retried automatically and causes an exception to be thrown to the application:
Traceback (most recent call last):
File ".venv/lib/python3.11/site-packages/pinecone/grpc/base.py", line 150, in wrapped
return func(
^^^^^
File ".venv/lib64/python3.11/site-packages/grpc/_channel.py", line 1181, in __call__
return _end_unary_response_blocking(state, call, False, None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".venv/lib64/python3.11/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
raise _InactiveRpcError(state)  # pytype: disable=not-instantiable …
> gRPC: Allow retries of up to MAX_MSG_SIZE

- pinecone/utils/user_agent.py
- tests/unit/utils/test_user_agent.py
Some partners have requested that colon, `:`, be added to the set of allowed characters inside source tags.
Add colon to the set of allowed characters.
Unit tests updated to reflect new allowed character.
> Allow colon inside source tags

- pinecone/grpc/base.py
- tests/unit_grpc/test_grpc_index_initialization.py
For an Index gRPC connection, port 443 is blindly added to the configured host for setting up the endpoint. A user should be able to specify a port for connection.
This PR will no longer append ":443" to the configured gRPC endpoint if a colon is already present in the host configuration.
Unit tests were updated for omitting and including a port in the host config. Verified that the client could connect to an Index on a port other than 443.
> do not override port if defined in host

- .github/workflows/testing-integration.yaml
- poetry.lock
- pyproject.toml
- tests/integration/inference/conftest.py
- tests/integration/inference/test_embed.py
We want to ship inference as part of the core SDK
Add a dependency on v1.0.2 of the inference plugin, which includes a recent fix to plugin installation for use with the GRPC client.
The plugin should automatically be installed and available for usage.
```python
pc = Pinecone(api_key='key')
embedding_model = "multilingual-e5-large"
embeddings = pc.inference.embed(
model=embedding_model,
inputs=["The quick brown fox jumps over the lazy dog.", "lorem ipsum"],
parameters={"input_type": "query", "truncate": "END"},
)
```
See tests passing.
> Add inference plugin and tests

- .github/workflows/release.yaml
We want documentation to automatically stay up to date after every release
Trigger the docs publish workflow after a new artifact is released to pypi
> [CI] Publish doc updates after each release

- pinecone/core/openapi/shared/rest.py
- tests/integration/data/conftest.py
- tests/integration/data/seed.py
- tests/integration/data/test_weird_ids.py
Some data operations fail when the vector id string contains a space.
```python
pc = Pinecone()
pc.fetch(ids=["id with string"]) # no results returned, even when vector exists
```
The problem occurred due to the way spaces were being encoded as `+` instead of `%20` in url query params. The fix was a small adjustment to our code generation templates.
I added test coverage for upsert / query / fetch with various weird ids to make sure the change in encoding hasn't broken any other use cases that could pop up.
> [Fix] Fetch when vector id string contains spaces

- pinecone/data/index.py
- pinecone/grpc/index_grpc.py
The dataframe column is `values`, not `vectors`.
```
from pinecone import Pinecone, ServerlessSpec
from pinecone_datasets import list_datasets, load_dataset
pc = Pinecone(api_key="xxx")
dataset = load_dataset("quora_all-MiniLM-L6-bm25")
print(dataset.head())
```
```
id                                             values  \
0  1  [0.06814987, -0.039664183, -0.06096721, 0.0074...
1  2  [0.08983771, -0.03493085, -0.057357617, 0.0222...
2  3  [-0.046798065, 0.1551149, -0.03920019, 0.04878...
3  4  [-0.077349104, 0.14786911, -0.0128817065, -0.0...
4  5  [-0.028324936, 0.037209604, -0.00040033547, 0....
sparse_values metadata  \
0  {'indices': [7096, 8508, 13677, 23041, 24734, ...     None
1  {'indices': [7096, 8508, 13677, 24734, 26026, ...     None
2  {'indices': [6065, 13677, 17109, 20780, …
```
> Fix dataframe column name in doc strings

- README.md
We are inconsistent in how we refer to our client libraries. 
As we mostly refer to our "SDKs" rather than our "clients", we've updated our docs to prefer "SDK". This PR makes equivalent updates to the Python README.
Addresses: https://app.asana.com/0/1206419570114940/1207978475519546/f
> Change "client" to "SDK" in README

- pinecone/control/__init__.py
- pinecone/control/pinecone.py
- pinecone/control/repr_overrides.py
- pinecone/models/collection_list.py
- pinecone/models/index_list.py
- pinecone/models/index_model.py
When running in notebooks, output from the `list_indexes` and `list_collections` commands created confusion because the `__repr__` representation for these objects showed an object with a top-level key that implied the response should be interacted with like a dictionary. This expectation contradicts with the way the `__iter__` implementations on these results objects are set up to enable iterating over results without drilling down. 
The origin of the complexity here is that the backing APIs used to return simple arrays of names that could be easily iterated over, and earlier this year they become more fleshed out responses. Returning more data is useful in some situations, but in trying to smooth out the impact of the API change and maintain a similar way of interacting with the …
> Improve output from list/describe actions on indexes and collections

- pinecone/grpc/base.py
- pinecone/grpc/channel_factory.py
- tests/unit_grpc/test_channel_factory.py
I'm preparing to implement asyncio for the data plane, and I had a need to extract some of this grpc channel configuration into a spot where it could be reused more easily across both sync and async implementations.
- Extract `GrpcChannelFactory` from `GRPCIndexBase`
- Add some unit tests for this new class
> [Refactor] Extract GrpcChannelFactory from GRPCIndexBase

- pinecone/grpc/base.py
- pinecone/grpc/grpc_runner.py
- pinecone/grpc/index_grpc.py
- tests/unit_grpc/test_grpc_index_describe_index_stats.py
- tests/unit_grpc/test_grpc_index_fetch.py
- tests/unit_grpc/test_grpc_index_initialization.py
- tests/unit_grpc/test_grpc_index_query.py
- tests/unit_grpc/test_grpc_index_update.py
- tests/unit_grpc/test_grpc_index_upsert.py
- tests/unit_grpc/test_runner.py
This is another extractive refactoring in preparation for grpc with asyncio.
The generated stub class, `VectorServiceStub`, is what knows how to call the Pinecone grpc service, but our wrapper code needs to do some work to make sure we have a consistent approach to "metadata" (grpc-speak for request headers) and handling other request params like `timeout`. Previously this work was accomplished in a private method of the `GRPCIndexBase` base class called `_wrap_grpc_call()`. 
Since we will need to perform almost identical marshaling of metadata for requests with asyncio, I pulled this logic out into a separate class `GrpcRunner` and renamed `_wrap_grpc_call` to `run`. You can see there is also a parallel method implementation called `run_asyncio`; currently this is unused and untested, …
> [Refactor] Extract GrpcRunner from GRPCIndexBase class

- .github/workflows/lint.yaml
- scripts/create.py
- tests/integration/control/pod/conftest.py
- tests/integration/control/pod/test_collections.py
- tests/integration/control/pod/test_collections_errors.py
- tests/integration/data/conftest.py
- tests/integration/helpers/__init__.py
- tests/integration/helpers/helpers.py
Sometimes indexes and collections aren't cleaned up properly after tests run. It's difficult to clean up orphaned resources without potentially impacting resources associated with tests that are currently running.
Modify generated names to include a timestamp. This will pave the way for automatically deleting orphaned resources after a certain period of time.
> [Chore] Put date into test index and collection names

- .github/workflows/cleanup-nightly.yaml
- scripts/cleanup-all.py
Sometimes when test cleanup steps fail, indexes and collections get left behind.
Create a nightly job to cleanup leftover indexes. Inspect the names of each index and collection to see whether they are more than 24 hours old prior to deleting. This should prevent deleting resources out from underneath any tests that may be running at the same time as the delete job.
> [Chore] Automatically cleanup old resources each night

- .github/actions/cleanup-all/action.yml
- scripts/cleanup-all.py
- tests/dependency/grpc/test_sanity.py
- tests/dependency/rest/test_sanity.py
- tests/integration/control/pod/conftest.py
- tests/integration/control/pod/test_collections.py
- tests/integration/control/pod/test_deletion_protection.py
- tests/integration/control/serverless/test_create_index_timeouts.py
- tests/integration/control/serverless/test_describe_index.py
I frequently see recurring test flakes, most often at the cleanup stage of `test_configure_index_with_deletion_protection` because the index cannot be deleted while still in an "upgrading" state. The index is in that state while configuration changes are being applied.
- In deletion protection test, wait for the index to be ready before attempting the delete.
- In dependency tests which do a basic sanity test, loosen the assertions. We're not really intending to test the backend functionality with these tests; we just want to make sure network calls are successfully made with a variety of different grpc / protobuff / etc dependency versions.
- Remove some assertions that rely on non-deterministic behavior on the backend. E.g. how long it takes for a serverless index to be considered …
> [Chore] Improve test flakes

- pinecone/grpc/__init__.py
- pinecone/grpc/future.py
- pinecone/grpc/index_grpc.py
- pinecone/grpc/utils.py
- tests/integration/data/test_delete_future.py
- tests/integration/data/test_fetch_future.py
- tests/integration/data/test_upsert_future.py
- tests/unit_grpc/test_futures.py
- tests/unit_grpc/test_grpc_index_upsert.py
`GRPCIndex` has long had limited and poorly documented support for async operations via the futures interface of the [`grpc`](https://grpc.github.io/grpc/python/grpc.html#grpc.UnaryUnaryMultiCallable.future) library. I've recently been trying to implement `query_namespaces` using these futures, and discovered that unfortunately the grpc futures implementation is not compatible with the `concurrent.futures` package in the standard library. This makes them pretty much useless for anything at all complicated because the grpc library doesn't provide any utils for synchronization or waiting.
A class called `PineconeGrpcFuture` was added in the past as a minimal wrapper around the [future](https://grpc.github.io/grpc/python/grpc.html#future-interfaces) that is emitted by `grpc`. These futures …
> [feat] PineconeGrpcFuture implements concurrent.futures.Future

- .github/actions/test-data-plane/action.yaml
- .github/workflows/testing-integration.yaml
- tests/integration/control/serverless/test_create_index_timeouts.py
- tests/integration/data/conftest.py
- tests/integration/data/test_weird_ids.py
We have a very large test matrix to check that different kinds of strings are handled properly. But we probably don't get that much value out of running these for every single PR.
Gate these tests on a boolean so I can only run these when desired instead of on every PR. It's most relevant to run them when changing dependencies or python versions.
> Disable tests for weird ids string encoding

- poetry.lock
- pyproject.toml
I need to release 5.4 without any breaking dependency changes.
Temporarily revert 1d0f046, which introduced a breaking change in dependencies
> Temporarily downgrade protobuf

- pinecone/core/openapi/shared/api_client.py
- pinecone/data/index.py
- pinecone/data/query_results_aggregator.py
- pinecone/grpc/index_grpc.py
- tests/integration/data/conftest.py
- tests/integration/data/test_query_namespaces.py
- tests/unit/test_query_results_aggregator.py
Sometimes people would like to run a query across multiple namespaces
Run a query for each namespace in parallel, then merge the results using a heap
```python
import random
pc = Pinecone(api_key='api-key')
index = pc.Index(
host="https://indexhost/",
pool_threads=10
)
query_vec = [random.random()] * dimension
combined_results = index.query_namespaces(
vector=query_vec,
namespaces=["ns1", "ns2", "ns3", "ns4"],
include_values=False,
include_metadata=True,
filter={"publication_date": {"$eq":"Last3Months"}},
top_k=100
)
```
A grpc implementation of this will follow in a separate PR. I have WIP on it, but some mypy type issues were causing me headaches and I'd rather land this stuff first.
Added integration tests
> Add `query_namespaces`

- pinecone/core/openapi/shared/api_client.py
- pinecone/core/openapi/shared/configuration.py
- pinecone/data/index.py
- poetry.lock
- pyproject.toml
- tests/perf/test_query_namespaces.py
- tests/perf/test_query_results_aggregator.py
Want to improve the performance of the rest implementation of `query_namespaces`
- Add `pytest-benchmark` dev dependency and some basic performance tests to interrogate the impact of certain changes. For now these are only run on my local machine, but in the future these could potentially be expanded into an automated suite.
- Pass `_preload_content=False` to tell the underlying generated code not to instantiate response objects for all the intermediate results.
- Use `ThreadPoolExecutor` instead of older `ThreadPool` implementation from multiprocessing. This involved some changes to the generated code, but the benefit of this approach is that you get back a `concurrent.futures.Future` instead of an `ApplyResult` which is much more ergonomic. I'm planning to extract the edited files out …
> query_namespaces performance improvements

- pinecone/control/pinecone.py
- pinecone/data/index.py
- pinecone/data/interfaces.py
- tests/integration/control/serverless/test_index_instantiation_ux.py
- tests/unit/test_index.py
Sometimes users incorrectly instantiate the Index client like this:
```python
import pinecone
index = pinecone.Index(index_name, host=index_host)
```
Then they will later get an authentication exception when using it, since the `Index` class does not have the configuration values it needs when attempting to perform vector operations.
```python
ForbiddenException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 13 Nov 2024 02:06:45 GMT', 'Content-Type': 'text/plain', 'Content-Length': '9', 'Connection': 'keep-alive', 'x-pinecone-auth-rejected-reason': 'Wrong API key', 'www-authenticate': 'Wrong API key', 'server': 'envoy'}) HTTP response body: Forbidden
```
- Rename the `Index` implementation to `_Index` so that people will not accidentally interact with it.
- …
> [Feat] Helpful error when incorrectly instantiating Index client

- pinecone/data/__init__.py
- pinecone/data/import_error.py
- pinecone/data/index.py
- pinecone/data/request_factory.py
- pinecone/openapi_support/__init__.py
- pinecone/openapi_support/constants.py
With my asyncio client in progress (not in this diff), I found myself needing to reuse a lot of the openapi request-building boilerplate.
Rather than copy/paste and create a lot of duplication, I want to pull that logic out into a separate class for building request objects. This change should not break existing behavior in the Index client.
This was pretty much just a mechanical extraction. I'd like to cleanup and standardize some stuff regarding `_check_type`, an openapi param that we're going to silly lengths to flip the default behavior on, in a follow-up diff.
Should still have tests passing
> [Refactor] Extract index request factory

- pinecone/data/index.py
- pinecone/data/query_results_aggregator.py
- pinecone/grpc/index_grpc.py
- tests/integration/data/test_query_namespaces.py
- tests/unit/test_query_results_aggregator.py
In order to merge results across multiple queries, the SDK must know which similarity metric an index is using. For dotproduct and cosine indexes, a larger score is better while for euclidean a smaller score is better. Unfortunately the data plane API does not currently expose the metric type and a separate call to the control plane to find out seems undesirable from a resiliency and performance perspective.
As a workaround, in the initial implementation of `query_namespaces` the SDK would infer the similarity metric needed to merge results by seeing whether the scores of query results were ascending or descending. This worked well, but imposes an implicit limitation that there must be at least 2 results returned. 
We initially believed this would not be a problem but have since learned …
> [Bug] query_namespaces can handle single result

- pinecone/data/__init__.py
- pinecone/data/index.py
- tests/unit/test_index.py
By renaming the `Index` class to `_Index` in https://github.com/pinecone-io/pinecone-python-client/pull/418, I accidentally broke plugin installation.
Rename the class back to `Index` and instead alias it to `_Index` through import statements. We still need to alias it within the `pinecone/data/__init__.py` module definition to avoid collision with the Index class designed to give users a more informative error when they incorrectly import the `Index` class from the `pinecone` module.
I went ahead and also cleaned up some stuff where we were unnecessarily exposing some internal openapi details in the public interface. Users should never realistically need to construct openapi request objects.
> [Fix] Rename Index class to fix plugin installation

- pinecone/__init__.py
- pinecone/control/pinecone.py
- pinecone/control/pinecone_interface.py
- pinecone/enums/__init__.py
- pinecone/enums/clouds.py
- pinecone/enums/deletion_protection.py
- pinecone/enums/metric.py
- pinecone/enums/pod_index_environment.py
- pinecone/enums/pod_type.py
- pinecone/enums/vector_type.py
- pinecone/models/__init__.py
- pinecone/models/clouds.py
- pinecone/models/pod_spec.py
- pinecone/models/serverless_spec.py
- tests/integration/control/serverless/conftest.py
- tests/integration/control/serverless/test_configure_index_deletion_protection.py
- tests/integration/control/serverless/test_create_index_sl_happy_path.py
- tests/unit/models/test_index_model.py
- tests/unit/test_control.py
Many configuration fields take string inputs even though there is a limited range of accepted values. It's poor UX having to go into documentation or examples in order to know which string values are available. This also means support via type hints from code editors are not available to keep people moving quickly.
- Create Enum classes for control plane configuration fields under `pinecone.enum`:
- General index configs: `Metric`, `VectorType`, `DeletionProtection`
- Serverless spec: `CloudProvider`, `AwsRegion`, `GcpRegion`, `AzureRegion`
- Pod spec: `PodIndexEnvironment`, `PodType`
kwargs that accept these values are loosely typed as the union of the enum type and string. This should prevent unnecessary breaking changes and maintain flexibility to accept new values that may not be …
> Define enum classes with control plane configuration options

- .github/actions/setup-poetry/action.yml
- .github/actions/test-data-asyncio/action.yaml
- .github/actions/test-dependency-asyncio-rest/action.yaml
- .github/workflows/testing-integration-asyncio.yaml
- .github/workflows/testing-integration.yaml
- .github/workflows/testing-unit.yaml
- pinecone/openapi_support/rest_aiohttp.py
- poetry.lock
- pyproject.toml
Rather than adding a new dependency for everyone, we want asyncio to be an extras install similar to how grpc is handled.
Adjust pyproject.toml to migrate aiohttp into an asyncio extras that will be installed like `pinecone[asyncio]`. Adjust test configuration to install the required dependencies.
> Move asyncio deps into extras

- pinecone/control/pinecone.py
- pinecone/control/pinecone_asyncio.py
- pinecone/control/pinecone_interface_asyncio.py
- tests/integration/control/serverless/test_index_instantiation_ux.py
- tests/unit/data/test_instantiation.py
- tests/unit/test_config.py
- tests/unit/test_config_builder.py
- tests/unit/test_control.py
- tests/unit/test_index_initialization.py
- tests/unit_grpc/test_grpc_index_describe_index_stats.py
- tests/unit_grpc/test_grpc_index_fetch.py
- tests/unit_grpc/test_grpc_index_initialization.py
- tests/unit_grpc/test_grpc_index_query.py
- tests/unit_grpc/test_grpc_index_update.py
- tests/unit_grpc/test_grpc_index_upsert.py
We want to deprecate a few kwargs and give more helpful error messages.
- Deprecate `config` and `openapi_config` kwargs; as far as I know these were only used for tests. They have not appeared in documentation. It adds quite a bit of complexity trying to merge configuration from all these sources so going forward we would prefer to just expect configuration from a single source, which are named kwargs.
- Add `NotImplementedError` messages that clearly explain some features that are not implemented yet for PineconeAsyncio. This is preferrable to allowing users to pass kwargs that have no effect, then getting frustrated when they seem not to work.
- Give more informative error when it looks like the user has passed an invalid value as the host
> Adjust config kwargs to Pinecone and PineconeAsyncio

- pinecone/__init__.py
- pinecone/data/index.py
- pinecone/data/index_asyncio.py
- pinecone/grpc/index_grpc.py
- pinecone/utils/tqdm.py
- poetry.lock
- pyproject.toml
- tests/integration/data/test_upsert_from_dataframe.py
We want to minimize the number of required dependencies we have, and tqdm is non-essential. Moreover, common notebook environments like Google Colab will already have tqdm loaded even if we do not declare this an explicit dependency.
Instead of having a specific dependency on tqdm, we want to detect and use it if it is available in the environment. Otherwise just noop with a stub implementation of our own.
> Remove explicit tqdm dependency

- pinecone/control/pinecone.py
- pinecone/control/pinecone_asyncio.py
- pinecone/openapi_support/rest_aiohttp.py
- pinecone/openapi_support/rest_urllib3.py
Need to wire up several properties that pass configurations in to the underlying aiohttp library.
Wire up several properties for `PineconeAsyncio` that are already supported in `Pinecone`: 
- `additional_headers` to pass extra headers on each request. Useful for internal testing.
- `ssl_verify` to turn off ssl verification. Sometimes useful for testing.
- `proxy_url` to send traffic through a proxy
- `ssl_ca_certs` to specify a custom cert bundle. Expecting a path to a PEM file.
Currently `proxy_headers` is not accepted by `PineconeAsyncio` because I haven't figured out how to use these with aiohttp.
> Expose SSL configurations for PineconeAsyncio

- pinecone/data/features/inference/inference.py
- pinecone/data/features/inference/inference_asyncio.py
- pinecone/data/features/inference/models/__init__.py
- pinecone/data/features/inference/models/embedding_list.py
- pinecone/data/features/inference/models/rerank_result.py
- tests/integration/inference/test_asyncio_inference.py
- tests/integration/inference/test_inference.py
When migrating the `embed` and `rerank` over from the plugin, I forgot to include these custom return objects.
Add custom return types, adjust tests to ensure result is iterable.
> [Fix] Return type from embed() should be iterator

- pinecone/openapi_support/configuration.py
While cleaning up and simplifying the Configuration class (which originated from generated code but is now something we maintain by hand for greater control), a congif attribute in use by the assistants plugin was accidentally removed.
Restore config attributes being used by assistants
> [WIP] KE compatibility

- docs/upgrading.md
The `PineconeAsyncio` example in the upgrading doc includes an extra `async` call. 
Remove the extra call.
> [docs] Remove extra async call in PineconeAsyncio example

- README.md
- docs/upgrading.md
The rename of the package from `pinecone-client` to `pinecone` is confusing.
Add information to the README that should hopefully help steer people in the right direction.
> Add information to README about package rename

- .github/actions/build-docs/action.yml
- .github/actions/build-docs/fix-relative-links.py
- pdoc/README.md
- pinecone/__init__.py
- pinecone/data/features/inference/inference.py
- pinecone/data/features/inference/inference_asyncio.py
- pinecone/grpc/index_grpc.py
- poetry.lock
- pyproject.toml
In the rendered static site at https://sdk.pinecone.io/python, links from within the README to other markdown files in the github repo are currently broken links.
- Add `beautifulsoup4` as dev dependency to enable parsing generated docs pages
- After the docs build, find relative links pointing to markdown files and replace the path with a github url.
- Setup a different flavor of the README specifically for pdoc to link to the most important parts of the reference docs
- Make a few docs tweaks (mainly adding `@private` annotations in a few places to hide clutter)
> Fix relative links in reference documentation

- README.md
There were no info on assistant in the readme
Now there is info on assistant in the readme
> [KE] Add assistant description

- pinecone/utils/user_agent.py
- tests/unit/utils/test_setup_openapi_client.py
- tests/unit/utils/test_user_agent.py
- Currently we send urllib3 version in the user agent string
- Testing with importtime shows importing urllib3 just to get the version extends the initial load time of the pinecone package by about 35 milliseconds.
I confirmed we're not using this information in the header, so we should remove it to improve initialization performance.
- Analysis with showed Loading this urllib3 to get the version was adding 35 milliseconds to the time needed to "from pinecone import Pinecone"
- Updated unit tests
> Remove urllib3 info from useragent string

- pinecone/__init__.py
- pinecone/db_control/models/__init__.py
- pinecone/db_control/models/byoc_spec.py
- pinecone/db_control/request_factory.py
- pinecone/db_control/resources/asyncio/index.py
- pinecone/db_control/resources/sync/index.py
- pinecone/legacy_pinecone_interface.py
- pinecone/pinecone.py
- pinecone/pinecone_asyncio.py
- pinecone/pinecone_interface_asyncio.py
- tests/unit/db_control/test_index.py
- tests/unit/db_control/test_index_request_factory.py
BYOC requires a new type of spec object, `ByocSpec`.
- Update legacy-style methods to accept new `ByocSpec` type:
- `Pinecone#create_index`
- `PineconeAsyncio#create_index`
- Update resource classes (accessed from `pc.db.index.create`)
- `IndexResource#create`
- `AsyncioIndexResource#create`
- Update interfaces used for docgen
- Added a new unit test to ensure the client can properly deserialize API responses (e.g. from describe, list) that include the new byoc spec type into the `IndexModel` object. This is important since I'm currently not set up to do a full integration test of the feature.
> Add BYOC support to `create_index`, `describe_index`, `list_indexes`

- pinecone/config/openapi_configuration.py
- pinecone/utils/error_handling.py
We want to continue improving our import and initialization times.
- Refactor the `@validate_and_convert_errors` decorator to use lazy-loading of `urllib3`. We only need to load urllib3 in this decorator at the moment an exception has occurred.
- Refactor `pinecone.config.openapi_configuration.py` to avoid loading the `http` module unless enabling debug logging. The default http log level is already 0 (disabled) so there's no need to set it in the default case.
```sh
poetry run python3 -X importtime -c "from pinecone import Pinecone; pc = Pinecone(api_key='foo')" 2> main.log
```
Comparing the importtime results before and after this change shows a reduction from 101ms to 65ms, **a savings of 36ms which is about 36%.**
> Use lazy loading in error decorator, debugging config

- README.md
- docs/upgrading.md
Need to update docs for release
> Update the `upgrading.md` doc with v7 release notes

- pinecone/grpc/future.py
- tests/unit_grpc/test_futures.py
When using grpc with `async_req=True`, the construction of a `PineconeGrpcFuture` would call `_sync_state`, which would do a blocking call to `grpc_future.exception(...)`. This means that the async reqs were all blocking in practice.
Describe the purpose of this change. What problem is being solved and why?
We can fix it by checking if the future is still running and not doing any blocking calls when it is.
How I tested it:
- Before: Run a long query in a loop and hit ctrl-c. Observe the traceback containing `PineconeGrpcFuture()`
- After: Run a long query in a loop and hit ctrl-c. Observe the traceback containing your `.result()` call instead.
> Fix: PineconeGrpcFuture blocks during construction

- pinecone/__init__.py
- pinecone/__init__.pyi
- pinecone/exceptions/__init__.py
- pinecone/exceptions/exceptions.py
- pinecone/pinecone.py
While implementing lazy loading and a package level .pyi file, we accidentally broke intellisense for some classes.
- Add missing exceptions to pyi
- Remove type annotations on `pc.inference` that rely on values imported during `TYPE_CHECKING`. It seems like mypy and intellisense/autocomplete are able to infer these types without them being labeled explicitly. I think there is some sort of bug in the way autocomplete works because these type hints used with [TYPE_CHECKING](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) are valid and seem to work for typechecking purposes. 
Made a `7.0.1.dev1` dev build to confirm autocomplete behavior in different environments
> Fix inference autocomplete
